#' Creates Matrix to Store Anterior Information
#'
#' Returns a matrix with \code{n} rows (individuals) and \code{|U|} columns, where the 
#' \code{(i,j)}th entry stores anterior probability(\code{i}, \code{u_j})
#' @param PG candidate genotypes generated by \code{pp.possibleGenotypes}
#' @param ped the pedigree
#' @param prev a vector of genotype prevalences (see \code{pp.prevalences})
#' @details Author: Tom Madsen
#' 
#' Pre-processing function
#' @family peeling
pp.initializeA = function(PG, ped, prev){
  A = matrix(NA, nrow=nrow(ped), ncol=nrow(PG))
  for(i in 1:nrow(ped)){
    if(ped$FatherID[i]==0 & ped$MotherID[i]==0){
      A[i,]=prev
    }
  }
  return(A)
}