#' Compute Probabilities of Inheriting Candidate Genotypes
#' 
#' Returns a 3D array. Entry (\code{ijk}) is the probability of inheriting genotype 
#' \code{k}, given that your parents have genotypes \code{i} and \code{j}
#' @param (\code{PG}) candidate genotypes generated by \code{pp.possibleGenotypes}.
#' @details Author: Tom Madsen
#' 
#' Pre-processing function
#' @family peeling
pp.inheritanceProb = function(PG){
  n_genotypes = nrow(PG)
  n_genes = ncol(PG)
  TR = array(0, rep(n_genotypes,3)) #the array to be returned
  
  M = array(0, dim=c(3,3,3))
  M[,,1] = matrix(c(1, 0.5, 0, 0.5, 0.25, 0, 0, 0, 0), nrow=3)
  M[,,2] = matrix(c(0, 0.5, 1, 0.5, 0.5, 0.5, 1, 0.5, 0), nrow=3)
  M[,,3] = matrix(c(0, 0, 0, 0, 0.25, 0.5, 0, 0.5, 1), nrow=3)
  
  for(i in 1:n_genotypes){
    u_f = PG[i,] #rows of PG represent genotypes
    for(j in 1:i){
      u_m = PG[j,]
      for(l in 1:n_genotypes){
        u = PG[l,]
        prod = 1
        for(k in 1:n_genes){
          prob = M[(u_f[k]+1),(u_m[k]+1),(u[k]+1)]
          if(prob==0){
            prod = 0
            break
          }else{
            prod = prod*prob
          }
        }
        TR[i,j,l] = prod
      }
      TR[j,i,]=TR[i,j,]
    }
  }
  return(TR)
}
