#' Creates 3D Array to Store Posterior Information
#' 
#' Returns a 3D array whose \code{(i,j,k)}th component stores \code{p_ij(u_k)}
#' @param PG candidate genotypes generated by \code{pp.possibleGenotypes}
#' @param E edge matrix (binary matrix which tells you who's mated with whom)
#' @details Author: Tom Madsen
#' 
#' Pre-processing function
#' @family peeling
pp.initializeP = function(PG, E){
  P = array(NA, c(nrow(E), nrow(E), nrow(PG)))
  for(i in 1:nrow(E)){
    for(j in 1:i){
      if(E[i,j]==0){
        P[i,j,]=1
      } else if (E[j,i]==0) {
        P[j,i,]=1
      }
    }
  }
  return(P)
}