#' Compute Prevalences for Each Admissible Genotype
#' 
#' Returns a vector containing the prior probability of each admissible genotype
#' @param MAFs the marginal prevalence of each mutation (i.e. a vector of length 
#' \code{k})
#' @param PG candidate genotypes generated by \code{pp.possibleGenotypes}
#' @details Author: Tom Madsen
#' 
#' Pre-processing function
#' @family peeling
pp.prevalences = function(MAFs, PG){
  k = length(MAFs)
  M = rbind((1-MAFs)^2, 2*MAFs*(1-MAFs), MAFs^2)
  prevs = c()
  for(i in 1:nrow(PG)){
    prev = 1
    for(j in 1:k){
      prev = prev*M[(PG[i,j]+1),j]
    }
    prevs[i] = prev
  }
  return(prevs)
}