#!/bin/bash
#SBATCH -J tophat #A single job name for the array
#SBATCH -o stdout.d/tophat_%A_%a.out #Standard output
#SBATCH -e stderr.d/tophat_%A_%a.err #Standard error
#SBATCH -p serial_requeue#Partition
#SBATCH -t 180 #Running time of 3 hours
#SBATCH --mem-per-cpu 3000 #Memory request
#SBATCH -n 4 #Number of cores
#SBATCH -N 1 #All cores on one machine


R CMD BATCH FrailtySim_RP_V03.R simrpv03_${SLURM_ARRAY_TASK_ID}.Rout
